env:
  browser: true
extends: 'react'
# parserOptions:
#  ecmaFeatures:
#    experimentalObjectRestSpread: true
#    jsx: true
#plugins:
#  - react
rules:
  indent:
    - error
    - 2
  #linebreak-style:
  #  - error
  #  - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
