[package]
name = "actix-web-test"
version = "0.1.0"
authors = ["Robert Collins <robertc@robertcollins.net>"]

[dependencies]
actix = "0.4"
actix-web = { version="0.3.3", features=["alpn"] }
openssl = { version="0.10", features = ["v110"] }
